apiVersion: apps/v1
kind: Deployment
metadata:
  name: robo-backend
  labels:
    app: robo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: robo-backend
  template:
    metadata:
      labels:
        app: robo-backend
    spec:
      containers:
        - name: backend
          image: najasoft/robo-backend:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
        