apiVersion: apps/v1
kind: Deployment
metadata:
  name: robo-backend
  labels:
    app: robo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: robo-backend
  template:
    metadata:
      labels:
        app: robo-backend
    spec:
      containers:
        - name: backend
          image: najasoft/robo-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: robo-mongo-secret
                  key: username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: robo-mongo-secret
                  key: password
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: robo-mongo-secret
                  key: database
            - name: MONGO_HOST
              value: "robo-mongo-service"  # Adjust the MongoDB service name as needed
              
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
        